### ISSUE TITLE
Падения на Ubuntu 17.10

### ISSUE THREAD

**Issue by Feliksas** [slytomcat/yandex-disk-indicator#184]
Периодически падает при показе уведомлений с таким трейсом:

```
Traceback (most recent call last):
   File "/usr/bin/yandex-disk-indicator", line 380, in iNhandle
     self._iNotifier.process_events()
   File "/usr/lib/python3/dist-packages/pyinotify.py", line 1275, in process_events
     self._default_proc_fun(revent)
   File "/usr/lib/python3/dist-packages/pyinotify.py", line 910, in __call__
     return _ProcessEvent.__call__(self, event)
   File "/usr/lib/python3/dist-packages/pyinotify.py", line 630, in __call__
     return meth(event)
   File "/usr/bin/yandex-disk-indicator", line 372, in process_IN_MODIFY
     handler(par)
   File "/usr/bin/yandex-disk-indicator", line 486, in _eventHandler
     self.change(self.vals)                  # Raise outside update event
   File "/usr/bin/yandex-disk-indicator", line 694, in change
     self.notify.send(_('Synchronization has been completed'))
   File "/usr/bin/yandex-disk-indicator", line 317, in send
     self.note.close()
 GLib.GError: g-io-error-quark: GDBus.Error:org.freedesktop.DBus.GLib.UnmappedError.NotificationDaemonErrorQuark.Code100: 0 is not a valid notification ID (36)
```

Не уверен, как правильнее это чинить, у себя закостылил пока так:

```diff
--- yandex-disk-indicator.orig.py	2018-02-01 14:07:33.607797701 +0300
+++ /usr/bin/yandex-disk-indicator	2018-02-01 14:00:49.089740131 +0300
@@ -32,7 +32,7 @@
 require_version('Notify', '0.7')
 from gi.repository import Notify
 require_version('GLib', '2.0')
-from gi.repository.GLib import timeout_add, source_remove
+from gi.repository.GLib import timeout_add, source_remove, GError
 require_version('GdkPixbuf', '2.0')
 from gi.repository.GdkPixbuf import Pixbuf
 from subprocess import check_output, call, CalledProcessError
@@ -314,7 +314,10 @@
     logger.debug('Message: %s | %s' % (self.title, messg))
     if self.note is not None:
       # if self.note.props.closed_reason = -1:
-      self.note.close()
+      try:
+          self.note.close()
+      except GError:
+          pass
       self.note = None
     try:                            # Create notification
       self.note = Notify.Notification.new(self.title, messg)
```

**Comment by slytomcat** [comment]
Да не костыль - вполне нормальное решение. Там собственно не важно как и закроется оно или нет.

**Comment by slytomcat** [comment]
Вечером залью обновление с фиксом на Launchpad.

**Comment by slytomcat** [comment]
Заливаю обновление на Launchpad (v1.9.17).
Релиз на Гите - 1.9.17

**Comment by slytomcat** [comment]
Залито на Launchpad для Trusty, Xenial, Bionic и Artful.
