### ISSUE TITLE
Crash on unconfigured daemon

### ISSUE THREAD

**Issue by slytomcat** [slytomcat/yandex-disk-indicator#192]
Indicator crashes after start on unconfigured daemon.

> $ yandex-disk-indicator -l10
> 2018-03-23 14:44:38,424 INFO     yandex-disk-indicator v.1.10.1
> 2018-03-23 14:44:38,424 DEBUG    Logging level: 10
> 2018-03-23 14:44:38,425 DEBUG    Config value read as: autostart = True
> 2018-03-23 14:44:38,425 DEBUG    Config value read as: notifications = True
> 2018-03-23 14:44:38,425 DEBUG    Config value read as: theme = False
> 2018-03-23 14:44:38,425 DEBUG    Config value read as: fmextensions = True
> 2018-03-23 14:44:38,425 DEBUG    Config value read as: daemons = /home/ivan/.config/yandex-disk/config.cfg
> 2018-03-23 14:44:38,425 INFO     Config read: /home/ivan/.config/yd-tools/yandex-disk-indicator.conf
> 2018-03-23 14:44:38,452 DEBUG    Config value read as: auth = /home/ivan/.config/yandex-disk/passwd
> 2018-03-23 14:44:38,452 INFO     Config read: /home/ivan/.config/yandex-disk/config.cfg
> Traceback (most recent call last):
>   File "/usr/bin/yandex-disk-indicator", line 1401, in <module>
>     indicators.append(Indicator(d, _('#%d ') % len(indicators) if len(daemons) > 1 else ''))
>   File "/usr/bin/yandex-disk-indicator", line 676, in __init__
>     super(Indicator, self).__init__(path, ID)
>   File "/usr/bin/yandex-disk-indicator", line 412, in __init__
>     if self.errorDialog(cfgFile) != 0:
> AttributeError: 'Indicator' object has no attribute 'errorDialog'

**Comment by slytomcat** [comment]
Fixed in 1.10.2 release on github
1.10.2 will be published on Launchpad in 5-7 hours.
